### ISSUE TITLE
Trying to get includePaths to work in _config.yml

### ISSUE THREAD

**Issue by gunkdesign** [knksmith57/hexo-renderer-sass#34]
I've been trying to get the includePaths of node-sass to work with this package in a new hexo-theme but failing miserably. I'm trying to use Foundations sites node module package and the @import keeps failing on my theme.

After testing on a normal non hexo site I got my paths right but what seems to be issue is how it is set up in the .yml file and if your wrapper supports include paths?

`#SASS
node_sass:
  outputStyle: nested
  precision: 4
  sourceComments: false
  includePaths:  
    - --include-path node-modules/foundation-sites/scss/
    - --include-path node-modules/foundation-sites/scss/util`

Or the Gist: [https://gist.githubusercontent.com/gunkdesign/2d46c9542e63258d594a4edb0e15a12d/raw/7933e030aef32e0eb1a56a428dfb84c49d6bf538/_config.yml](url)

**Comment by JLHwung** [comment]
Hi gunkdesign,

As is said on REAMD:
> Anything specified under the key node_sass in your _config.yml files will be passed directly to the sass.render() call.

So `hexo-renderer-sass` does pass the options to `node-sass`, as the configuration of `node-sass` is supplied by `hexo`, which internally uses `js-yaml` to parse YAML to a valid JavaScript object. Therefore the question is, how to represent
```js
node_sass: {
  includePaths: [
    "node-modules/foundation-sites/scss/",
    "node-modules/foundation-sites/scss/util"
}
```
in yaml. It turns out to be pretty straightforward, and you can check that the following yaml is valid on http://nodeca.github.io/js-yaml/.

```yml
node_sass:
  includePaths:
    - node-modules/foundation-sites/scss/
    - node-modules/foundation-sites/scss/util
```

I hope it can help. Feel free to reply if you have any other questions.

**Comment by gunkdesign** [comment]
Thanks, I had tried that last night but I think the paths were wrong, I ended up using bower as the source and this is the working code if anyone else has the same issue

  includePaths: 
   - bower_components/foundation-sites/scss/
   - bower_components/foundation-sites/scss/util 
   - include-path themes/portfolio/source/css

**Comment by JLHwung** [comment]
Hi gunkdesign,
Thank you for your tips. I am closing this issue as it is solved now.
