### ISSUE TITLE
Use the theme config

### ISSUE THREAD

**Issue by macoshita** [knksmith57/hexo-renderer-sass#9]
Thank you for the good plugin!

I feel it is better to use the theme config, like [hexo-renderer-less](https://github.com/hexojs/hexo-renderer-less.git).
In the global configuration, it would affect the other themes.

**Comment by knksmith57** [comment]
I think this is a great idea.

Rather than _move_ the config into the theme's `_config.yml`, I think it'd be more useful to allow for a chain of inherited overrides. Something like code defaults -> theme specifics -> global overrides.

This way, themes can configure sane defaults but the dev / user can always jump in and enforce a particular value at the top-level.

What do you think?

**Comment by knksmith57** [comment]
Let's see how you + the community like this. If removing the config options from the top level, or reordering the priority used for inheritance is the consensus, then I certainly have no objections and would be happy to oblige.

For now, this seems like a pretty solid balance between flexibility and backwards compatibility.

Thanks for the suggestion! :+1:

**Comment by macoshita** [comment]
LGTM :+1: 

Thank you for quick response!
